// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/ARPlusEncounterValues.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/ARPlusEncounterValues.proto</summary>
  public static partial class ARPlusEncounterValuesReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/ARPlusEncounterValues.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static ARPlusEncounterValuesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CitQT0dPUHJvdG9zL0RhdGEvQVJQbHVzRW5jb3VudGVyVmFsdWVzLnByb3Rv",
            "Eg9QT0dPUHJvdG9zLkRhdGEiWQoVQVJQbHVzRW5jb3VudGVyVmFsdWVzEhEK",
            "CXByb3hpbWl0eRgBIAEoAhIRCglhd2FyZW5lc3MYAiABKAISGgoScG9rZW1v",
            "bl9mcmlnaHRlbmVkGAMgASgIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.ARPlusEncounterValues), global::POGOProtos.Data.ARPlusEncounterValues.Parser, new[]{ "Proximity", "Awareness", "PokemonFrightened" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class ARPlusEncounterValues : pb::IMessage<ARPlusEncounterValues> {
    private static readonly pb::MessageParser<ARPlusEncounterValues> _parser = new pb::MessageParser<ARPlusEncounterValues>(() => new ARPlusEncounterValues());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ARPlusEncounterValues> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.ARPlusEncounterValuesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ARPlusEncounterValues() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ARPlusEncounterValues(ARPlusEncounterValues other) : this() {
      proximity_ = other.proximity_;
      awareness_ = other.awareness_;
      pokemonFrightened_ = other.pokemonFrightened_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ARPlusEncounterValues Clone() {
      return new ARPlusEncounterValues(this);
    }

    /// <summary>Field number for the "proximity" field.</summary>
    public const int ProximityFieldNumber = 1;
    private float proximity_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Proximity {
      get { return proximity_; }
      set {
        proximity_ = value;
      }
    }

    /// <summary>Field number for the "awareness" field.</summary>
    public const int AwarenessFieldNumber = 2;
    private float awareness_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float Awareness {
      get { return awareness_; }
      set {
        awareness_ = value;
      }
    }

    /// <summary>Field number for the "pokemon_frightened" field.</summary>
    public const int PokemonFrightenedFieldNumber = 3;
    private bool pokemonFrightened_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool PokemonFrightened {
      get { return pokemonFrightened_; }
      set {
        pokemonFrightened_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ARPlusEncounterValues);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ARPlusEncounterValues other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Proximity != other.Proximity) return false;
      if (Awareness != other.Awareness) return false;
      if (PokemonFrightened != other.PokemonFrightened) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Proximity != 0F) hash ^= Proximity.GetHashCode();
      if (Awareness != 0F) hash ^= Awareness.GetHashCode();
      if (PokemonFrightened != false) hash ^= PokemonFrightened.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Proximity != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(Proximity);
      }
      if (Awareness != 0F) {
        output.WriteRawTag(21);
        output.WriteFloat(Awareness);
      }
      if (PokemonFrightened != false) {
        output.WriteRawTag(24);
        output.WriteBool(PokemonFrightened);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Proximity != 0F) {
        size += 1 + 4;
      }
      if (Awareness != 0F) {
        size += 1 + 4;
      }
      if (PokemonFrightened != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ARPlusEncounterValues other) {
      if (other == null) {
        return;
      }
      if (other.Proximity != 0F) {
        Proximity = other.Proximity;
      }
      if (other.Awareness != 0F) {
        Awareness = other.Awareness;
      }
      if (other.PokemonFrightened != false) {
        PokemonFrightened = other.PokemonFrightened;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            Proximity = input.ReadFloat();
            break;
          }
          case 21: {
            Awareness = input.ReadFloat();
            break;
          }
          case 24: {
            PokemonFrightened = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
