// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/FoodValue.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/FoodValue.proto</summary>
  public static partial class FoodValueReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/FoodValue.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static FoodValueReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ch9QT0dPUHJvdG9zL0RhdGEvRm9vZFZhbHVlLnByb3RvEg9QT0dPUHJvdG9z",
            "LkRhdGEaJlBPR09Qcm90b3MvSW52ZW50b3J5L0l0ZW0vSXRlbUlkLnByb3Rv",
            "InMKCUZvb2RWYWx1ZRIbChNtb3RpdmF0aW9uX2luY3JlYXNlGAEgASgCEhMK",
            "C2NwX2luY3JlYXNlGAIgASgFEjQKCWZvb2RfaXRlbRgDIAEoDjIhLlBPR09Q",
            "cm90b3MuSW52ZW50b3J5Lkl0ZW0uSXRlbUlkYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Inventory.Item.ItemIdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.FoodValue), global::POGOProtos.Data.FoodValue.Parser, new[]{ "MotivationIncrease", "CpIncrease", "FoodItem" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class FoodValue : pb::IMessage<FoodValue> {
    private static readonly pb::MessageParser<FoodValue> _parser = new pb::MessageParser<FoodValue>(() => new FoodValue());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<FoodValue> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.FoodValueReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FoodValue() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FoodValue(FoodValue other) : this() {
      motivationIncrease_ = other.motivationIncrease_;
      cpIncrease_ = other.cpIncrease_;
      foodItem_ = other.foodItem_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public FoodValue Clone() {
      return new FoodValue(this);
    }

    /// <summary>Field number for the "motivation_increase" field.</summary>
    public const int MotivationIncreaseFieldNumber = 1;
    private float motivationIncrease_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public float MotivationIncrease {
      get { return motivationIncrease_; }
      set {
        motivationIncrease_ = value;
      }
    }

    /// <summary>Field number for the "cp_increase" field.</summary>
    public const int CpIncreaseFieldNumber = 2;
    private int cpIncrease_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CpIncrease {
      get { return cpIncrease_; }
      set {
        cpIncrease_ = value;
      }
    }

    /// <summary>Field number for the "food_item" field.</summary>
    public const int FoodItemFieldNumber = 3;
    private global::POGOProtos.Inventory.Item.ItemId foodItem_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Inventory.Item.ItemId FoodItem {
      get { return foodItem_; }
      set {
        foodItem_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as FoodValue);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(FoodValue other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (MotivationIncrease != other.MotivationIncrease) return false;
      if (CpIncrease != other.CpIncrease) return false;
      if (FoodItem != other.FoodItem) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (MotivationIncrease != 0F) hash ^= MotivationIncrease.GetHashCode();
      if (CpIncrease != 0) hash ^= CpIncrease.GetHashCode();
      if (FoodItem != 0) hash ^= FoodItem.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (MotivationIncrease != 0F) {
        output.WriteRawTag(13);
        output.WriteFloat(MotivationIncrease);
      }
      if (CpIncrease != 0) {
        output.WriteRawTag(16);
        output.WriteInt32(CpIncrease);
      }
      if (FoodItem != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) FoodItem);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (MotivationIncrease != 0F) {
        size += 1 + 4;
      }
      if (CpIncrease != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(CpIncrease);
      }
      if (FoodItem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) FoodItem);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(FoodValue other) {
      if (other == null) {
        return;
      }
      if (other.MotivationIncrease != 0F) {
        MotivationIncrease = other.MotivationIncrease;
      }
      if (other.CpIncrease != 0) {
        CpIncrease = other.CpIncrease;
      }
      if (other.FoodItem != 0) {
        FoodItem = other.FoodItem;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 13: {
            MotivationIncrease = input.ReadFloat();
            break;
          }
          case 16: {
            CpIncrease = input.ReadInt32();
            break;
          }
          case 24: {
            foodItem_ = (global::POGOProtos.Inventory.Item.ItemId) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
