// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/PokemonDisplay.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/PokemonDisplay.proto</summary>
  public static partial class PokemonDisplayReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/PokemonDisplay.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PokemonDisplayReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CiRQT0dPUHJvdG9zL0RhdGEvUG9rZW1vbkRpc3BsYXkucHJvdG8SD1BPR09Q",
            "cm90b3MuRGF0YSL7AQoOUG9rZW1vbkRpc3BsYXkSOAoHY29zdHVtZRgBIAEo",
            "DjInLlBPR09Qcm90b3MuRGF0YS5Qb2tlbW9uRGlzcGxheS5Db3N0dW1lEjYK",
            "BmdlbmRlchgCIAEoDjImLlBPR09Qcm90b3MuRGF0YS5Qb2tlbW9uRGlzcGxh",
            "eS5HZW5kZXISDQoFc2hpbnkYAyABKAgiJgoHQ29zdHVtZRIJCgVVTlNFVBAA",
            "EhAKDEhPTElEQVlfMjAxNhABIkAKBkdlbmRlchIQCgxHRU5ERVJfVU5TRVQQ",
            "ABIICgRNQUxFEAESCgoGRkVNQUxFEAISDgoKR0VOREVSTEVTUxADYgZwcm90",
            "bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.PokemonDisplay), global::POGOProtos.Data.PokemonDisplay.Parser, new[]{ "Costume", "Gender", "Shiny" }, null, new[]{ typeof(global::POGOProtos.Data.PokemonDisplay.Types.Costume), typeof(global::POGOProtos.Data.PokemonDisplay.Types.Gender) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class PokemonDisplay : pb::IMessage<PokemonDisplay> {
    private static readonly pb::MessageParser<PokemonDisplay> _parser = new pb::MessageParser<PokemonDisplay>(() => new PokemonDisplay());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<PokemonDisplay> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.PokemonDisplayReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PokemonDisplay() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PokemonDisplay(PokemonDisplay other) : this() {
      costume_ = other.costume_;
      gender_ = other.gender_;
      shiny_ = other.shiny_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public PokemonDisplay Clone() {
      return new PokemonDisplay(this);
    }

    /// <summary>Field number for the "costume" field.</summary>
    public const int CostumeFieldNumber = 1;
    private global::POGOProtos.Data.PokemonDisplay.Types.Costume costume_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.PokemonDisplay.Types.Costume Costume {
      get { return costume_; }
      set {
        costume_ = value;
      }
    }

    /// <summary>Field number for the "gender" field.</summary>
    public const int GenderFieldNumber = 2;
    private global::POGOProtos.Data.PokemonDisplay.Types.Gender gender_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.PokemonDisplay.Types.Gender Gender {
      get { return gender_; }
      set {
        gender_ = value;
      }
    }

    /// <summary>Field number for the "shiny" field.</summary>
    public const int ShinyFieldNumber = 3;
    private bool shiny_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Shiny {
      get { return shiny_; }
      set {
        shiny_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as PokemonDisplay);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(PokemonDisplay other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Costume != other.Costume) return false;
      if (Gender != other.Gender) return false;
      if (Shiny != other.Shiny) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Costume != 0) hash ^= Costume.GetHashCode();
      if (Gender != 0) hash ^= Gender.GetHashCode();
      if (Shiny != false) hash ^= Shiny.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Costume != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Costume);
      }
      if (Gender != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) Gender);
      }
      if (Shiny != false) {
        output.WriteRawTag(24);
        output.WriteBool(Shiny);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Costume != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Costume);
      }
      if (Gender != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Gender);
      }
      if (Shiny != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(PokemonDisplay other) {
      if (other == null) {
        return;
      }
      if (other.Costume != 0) {
        Costume = other.Costume;
      }
      if (other.Gender != 0) {
        Gender = other.Gender;
      }
      if (other.Shiny != false) {
        Shiny = other.Shiny;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            costume_ = (global::POGOProtos.Data.PokemonDisplay.Types.Costume) input.ReadEnum();
            break;
          }
          case 16: {
            gender_ = (global::POGOProtos.Data.PokemonDisplay.Types.Gender) input.ReadEnum();
            break;
          }
          case 24: {
            Shiny = input.ReadBool();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the PokemonDisplay message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Costume {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("HOLIDAY_2016")] Holiday2016 = 1,
      }

      public enum Gender {
        [pbr::OriginalName("GENDER_UNSET")] Unset = 0,
        [pbr::OriginalName("MALE")] Male = 1,
        [pbr::OriginalName("FEMALE")] Female = 2,
        [pbr::OriginalName("GENDERLESS")] Less = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
