// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Data/Battle/BattleParticipant.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Data.Battle {

  /// <summary>Holder for reflection information generated from POGOProtos/Data/Battle/BattleParticipant.proto</summary>
  public static partial class BattleParticipantReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Data/Battle/BattleParticipant.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static BattleParticipantReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Ci5QT0dPUHJvdG9zL0RhdGEvQmF0dGxlL0JhdHRsZVBhcnRpY2lwYW50LnBy",
            "b3RvEhZQT0dPUHJvdG9zLkRhdGEuQmF0dGxlGi5QT0dPUHJvdG9zL0RhdGEv",
            "QmF0dGxlL0JhdHRsZVBva2Vtb25JbmZvLnByb3RvGjBQT0dPUHJvdG9zL0Rh",
            "dGEvUGxheWVyL1BsYXllclB1YmxpY1Byb2ZpbGUucHJvdG8aKVBPR09Qcm90",
            "b3MvTWFwL1Bva2Vtb24vTG9iYnlQb2tlbW9uLnByb3RvIv8CChFCYXR0bGVQ",
            "YXJ0aWNpcGFudBJBCg5hY3RpdmVfcG9rZW1vbhgBIAEoCzIpLlBPR09Qcm90",
            "b3MuRGF0YS5CYXR0bGUuQmF0dGxlUG9rZW1vbkluZm8SSwoWdHJhaW5lcl9w",
            "dWJsaWNfcHJvZmlsZRgCIAEoCzIrLlBPR09Qcm90b3MuRGF0YS5QbGF5ZXIu",
            "UGxheWVyUHVibGljUHJvZmlsZRJCCg9yZXZlcnNlX3Bva2Vtb24YAyADKAsy",
            "KS5QT0dPUHJvdG9zLkRhdGEuQmF0dGxlLkJhdHRsZVBva2Vtb25JbmZvEkMK",
            "EGRlZmVhdGVkX3Bva2Vtb24YBCADKAsyKS5QT0dPUHJvdG9zLkRhdGEuQmF0",
            "dGxlLkJhdHRsZVBva2Vtb25JbmZvEjsKDWxvYmJ5X3Bva2Vtb24YBSADKAsy",
            "JC5QT0dPUHJvdG9zLk1hcC5Qb2tlbW9uLkxvYmJ5UG9rZW1vbhIUCgxkYW1h",
            "Z2VfZGVhbHQYBiABKAViBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Battle.BattlePokemonInfoReflection.Descriptor, global::POGOProtos.Data.Player.PlayerPublicProfileReflection.Descriptor, global::POGOProtos.Map.Pokemon.LobbyPokemonReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Data.Battle.BattleParticipant), global::POGOProtos.Data.Battle.BattleParticipant.Parser, new[]{ "ActivePokemon", "TrainerPublicProfile", "ReversePokemon", "DefeatedPokemon", "LobbyPokemon", "DamageDealt" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class BattleParticipant : pb::IMessage<BattleParticipant> {
    private static readonly pb::MessageParser<BattleParticipant> _parser = new pb::MessageParser<BattleParticipant>(() => new BattleParticipant());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<BattleParticipant> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Data.Battle.BattleParticipantReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleParticipant() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleParticipant(BattleParticipant other) : this() {
      ActivePokemon = other.activePokemon_ != null ? other.ActivePokemon.Clone() : null;
      TrainerPublicProfile = other.trainerPublicProfile_ != null ? other.TrainerPublicProfile.Clone() : null;
      reversePokemon_ = other.reversePokemon_.Clone();
      defeatedPokemon_ = other.defeatedPokemon_.Clone();
      lobbyPokemon_ = other.lobbyPokemon_.Clone();
      damageDealt_ = other.damageDealt_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public BattleParticipant Clone() {
      return new BattleParticipant(this);
    }

    /// <summary>Field number for the "active_pokemon" field.</summary>
    public const int ActivePokemonFieldNumber = 1;
    private global::POGOProtos.Data.Battle.BattlePokemonInfo activePokemon_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Battle.BattlePokemonInfo ActivePokemon {
      get { return activePokemon_; }
      set {
        activePokemon_ = value;
      }
    }

    /// <summary>Field number for the "trainer_public_profile" field.</summary>
    public const int TrainerPublicProfileFieldNumber = 2;
    private global::POGOProtos.Data.Player.PlayerPublicProfile trainerPublicProfile_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Player.PlayerPublicProfile TrainerPublicProfile {
      get { return trainerPublicProfile_; }
      set {
        trainerPublicProfile_ = value;
      }
    }

    /// <summary>Field number for the "reverse_pokemon" field.</summary>
    public const int ReversePokemonFieldNumber = 3;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Battle.BattlePokemonInfo> _repeated_reversePokemon_codec
        = pb::FieldCodec.ForMessage(26, global::POGOProtos.Data.Battle.BattlePokemonInfo.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> reversePokemon_ = new pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> ReversePokemon {
      get { return reversePokemon_; }
    }

    /// <summary>Field number for the "defeated_pokemon" field.</summary>
    public const int DefeatedPokemonFieldNumber = 4;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.Battle.BattlePokemonInfo> _repeated_defeatedPokemon_codec
        = pb::FieldCodec.ForMessage(34, global::POGOProtos.Data.Battle.BattlePokemonInfo.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> defeatedPokemon_ = new pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.Battle.BattlePokemonInfo> DefeatedPokemon {
      get { return defeatedPokemon_; }
    }

    /// <summary>Field number for the "lobby_pokemon" field.</summary>
    public const int LobbyPokemonFieldNumber = 5;
    private static readonly pb::FieldCodec<global::POGOProtos.Map.Pokemon.LobbyPokemon> _repeated_lobbyPokemon_codec
        = pb::FieldCodec.ForMessage(42, global::POGOProtos.Map.Pokemon.LobbyPokemon.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Map.Pokemon.LobbyPokemon> lobbyPokemon_ = new pbc::RepeatedField<global::POGOProtos.Map.Pokemon.LobbyPokemon>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Map.Pokemon.LobbyPokemon> LobbyPokemon {
      get { return lobbyPokemon_; }
    }

    /// <summary>Field number for the "damage_dealt" field.</summary>
    public const int DamageDealtFieldNumber = 6;
    private int damageDealt_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int DamageDealt {
      get { return damageDealt_; }
      set {
        damageDealt_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as BattleParticipant);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(BattleParticipant other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(ActivePokemon, other.ActivePokemon)) return false;
      if (!object.Equals(TrainerPublicProfile, other.TrainerPublicProfile)) return false;
      if(!reversePokemon_.Equals(other.reversePokemon_)) return false;
      if(!defeatedPokemon_.Equals(other.defeatedPokemon_)) return false;
      if(!lobbyPokemon_.Equals(other.lobbyPokemon_)) return false;
      if (DamageDealt != other.DamageDealt) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (activePokemon_ != null) hash ^= ActivePokemon.GetHashCode();
      if (trainerPublicProfile_ != null) hash ^= TrainerPublicProfile.GetHashCode();
      hash ^= reversePokemon_.GetHashCode();
      hash ^= defeatedPokemon_.GetHashCode();
      hash ^= lobbyPokemon_.GetHashCode();
      if (DamageDealt != 0) hash ^= DamageDealt.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (activePokemon_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(ActivePokemon);
      }
      if (trainerPublicProfile_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(TrainerPublicProfile);
      }
      reversePokemon_.WriteTo(output, _repeated_reversePokemon_codec);
      defeatedPokemon_.WriteTo(output, _repeated_defeatedPokemon_codec);
      lobbyPokemon_.WriteTo(output, _repeated_lobbyPokemon_codec);
      if (DamageDealt != 0) {
        output.WriteRawTag(48);
        output.WriteInt32(DamageDealt);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (activePokemon_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(ActivePokemon);
      }
      if (trainerPublicProfile_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(TrainerPublicProfile);
      }
      size += reversePokemon_.CalculateSize(_repeated_reversePokemon_codec);
      size += defeatedPokemon_.CalculateSize(_repeated_defeatedPokemon_codec);
      size += lobbyPokemon_.CalculateSize(_repeated_lobbyPokemon_codec);
      if (DamageDealt != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(DamageDealt);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(BattleParticipant other) {
      if (other == null) {
        return;
      }
      if (other.activePokemon_ != null) {
        if (activePokemon_ == null) {
          activePokemon_ = new global::POGOProtos.Data.Battle.BattlePokemonInfo();
        }
        ActivePokemon.MergeFrom(other.ActivePokemon);
      }
      if (other.trainerPublicProfile_ != null) {
        if (trainerPublicProfile_ == null) {
          trainerPublicProfile_ = new global::POGOProtos.Data.Player.PlayerPublicProfile();
        }
        TrainerPublicProfile.MergeFrom(other.TrainerPublicProfile);
      }
      reversePokemon_.Add(other.reversePokemon_);
      defeatedPokemon_.Add(other.defeatedPokemon_);
      lobbyPokemon_.Add(other.lobbyPokemon_);
      if (other.DamageDealt != 0) {
        DamageDealt = other.DamageDealt;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (activePokemon_ == null) {
              activePokemon_ = new global::POGOProtos.Data.Battle.BattlePokemonInfo();
            }
            input.ReadMessage(activePokemon_);
            break;
          }
          case 18: {
            if (trainerPublicProfile_ == null) {
              trainerPublicProfile_ = new global::POGOProtos.Data.Player.PlayerPublicProfile();
            }
            input.ReadMessage(trainerPublicProfile_);
            break;
          }
          case 26: {
            reversePokemon_.AddEntriesFrom(input, _repeated_reversePokemon_codec);
            break;
          }
          case 34: {
            defeatedPokemon_.AddEntriesFrom(input, _repeated_defeatedPokemon_codec);
            break;
          }
          case 42: {
            lobbyPokemon_.AddEntriesFrom(input, _repeated_lobbyPokemon_codec);
            break;
          }
          case 48: {
            DamageDealt = input.ReadInt32();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
