// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/AwardFreeRaidTicketResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/AwardFreeRaidTicketResponse.proto</summary>
  public static partial class AwardFreeRaidTicketResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/AwardFreeRaidTicketResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static AwardFreeRaidTicketResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkFQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL0F3YXJkRnJlZVJh",
            "aWRUaWNrZXRSZXNwb25zZS5wcm90bxIfUE9HT1Byb3Rvcy5OZXR3b3JraW5n",
            "LlJlc3BvbnNlcyKOAgobQXdhcmRGcmVlUmFpZFRpY2tldFJlc3BvbnNlElMK",
            "BnJlc3VsdBgBIAEoDjJDLlBPR09Qcm90b3MuTmV0d29ya2luZy5SZXNwb25z",
            "ZXMuQXdhcmRGcmVlUmFpZFRpY2tldFJlc3BvbnNlLlJlc3VsdCKZAQoGUmVz",
            "dWx0EhEKDU5PX1JFU1VMVF9TRVQQABILCgdTVUNDRVNTEAESKAokRVJST1Jf",
            "UExBWUVSX0RPRVNfTk9UX01FRVRfTUlOX0xFVkVMEAISJgoiRVJST1JfREFJ",
            "TFlfVElDS0VUX0FMUkVBRFlfQVdBUkRFRBADEh0KGUVSUk9SX1BMQVlFUl9P",
            "VVRfT0ZfUkFOR0UQBGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.AwardFreeRaidTicketResponse), global::POGOProtos.Networking.Responses.AwardFreeRaidTicketResponse.Parser, new[]{ "Result" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.AwardFreeRaidTicketResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class AwardFreeRaidTicketResponse : pb::IMessage<AwardFreeRaidTicketResponse> {
    private static readonly pb::MessageParser<AwardFreeRaidTicketResponse> _parser = new pb::MessageParser<AwardFreeRaidTicketResponse>(() => new AwardFreeRaidTicketResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<AwardFreeRaidTicketResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.AwardFreeRaidTicketResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AwardFreeRaidTicketResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AwardFreeRaidTicketResponse(AwardFreeRaidTicketResponse other) : this() {
      result_ = other.result_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public AwardFreeRaidTicketResponse Clone() {
      return new AwardFreeRaidTicketResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.AwardFreeRaidTicketResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.AwardFreeRaidTicketResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as AwardFreeRaidTicketResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(AwardFreeRaidTicketResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(AwardFreeRaidTicketResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.AwardFreeRaidTicketResponse.Types.Result) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the AwardFreeRaidTicketResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("NO_RESULT_SET")] NoResultSet = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_PLAYER_DOES_NOT_MEET_MIN_LEVEL")] ErrorPlayerDoesNotMeetMinLevel = 2,
        [pbr::OriginalName("ERROR_DAILY_TICKET_ALREADY_AWARDED")] ErrorDailyTicketAlreadyAwarded = 3,
        [pbr::OriginalName("ERROR_PLAYER_OUT_OF_RANGE")] ErrorPlayerOutOfRange = 4,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
