// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GetAssetDigestResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/GetAssetDigestResponse.proto</summary>
  public static partial class GetAssetDigestResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/GetAssetDigestResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetAssetDigestResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CjxQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL0dldEFzc2V0RGln",
            "ZXN0UmVzcG9uc2UucHJvdG8SH1BPR09Qcm90b3MuTmV0d29ya2luZy5SZXNw",
            "b25zZXMaJlBPR09Qcm90b3MvRGF0YS9Bc3NldERpZ2VzdEVudHJ5LnByb3Rv",
            "Iv0BChZHZXRBc3NldERpZ2VzdFJlc3BvbnNlEjEKBmRpZ2VzdBgBIAMoCzIh",
            "LlBPR09Qcm90b3MuRGF0YS5Bc3NldERpZ2VzdEVudHJ5EhQKDHRpbWVzdGFt",
            "cF9tcxgCIAEoBBJOCgZyZXN1bHQYAyABKA4yPi5QT0dPUHJvdG9zLk5ldHdv",
            "cmtpbmcuUmVzcG9uc2VzLkdldEFzc2V0RGlnZXN0UmVzcG9uc2UuUmVzdWx0",
            "EhMKC3BhZ2Vfb2Zmc2V0GAQgASgFIjUKBlJlc3VsdBIJCgVVTlNFVBAAEgsK",
            "B1NVQ0NFU1MQARIICgRQQUdFEAISCQoFUkVUUlkQA2IGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.AssetDigestEntryReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.GetAssetDigestResponse), global::POGOProtos.Networking.Responses.GetAssetDigestResponse.Parser, new[]{ "Digest", "TimestampMs", "Result", "PageOffset" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.GetAssetDigestResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetAssetDigestResponse : pb::IMessage<GetAssetDigestResponse> {
    private static readonly pb::MessageParser<GetAssetDigestResponse> _parser = new pb::MessageParser<GetAssetDigestResponse>(() => new GetAssetDigestResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetAssetDigestResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.GetAssetDigestResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetDigestResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetDigestResponse(GetAssetDigestResponse other) : this() {
      digest_ = other.digest_.Clone();
      timestampMs_ = other.timestampMs_;
      result_ = other.result_;
      pageOffset_ = other.pageOffset_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetAssetDigestResponse Clone() {
      return new GetAssetDigestResponse(this);
    }

    /// <summary>Field number for the "digest" field.</summary>
    public const int DigestFieldNumber = 1;
    private static readonly pb::FieldCodec<global::POGOProtos.Data.AssetDigestEntry> _repeated_digest_codec
        = pb::FieldCodec.ForMessage(10, global::POGOProtos.Data.AssetDigestEntry.Parser);
    private readonly pbc::RepeatedField<global::POGOProtos.Data.AssetDigestEntry> digest_ = new pbc::RepeatedField<global::POGOProtos.Data.AssetDigestEntry>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::POGOProtos.Data.AssetDigestEntry> Digest {
      get { return digest_; }
    }

    /// <summary>Field number for the "timestamp_ms" field.</summary>
    public const int TimestampMsFieldNumber = 2;
    private ulong timestampMs_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong TimestampMs {
      get { return timestampMs_; }
      set {
        timestampMs_ = value;
      }
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 3;
    private global::POGOProtos.Networking.Responses.GetAssetDigestResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.GetAssetDigestResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "page_offset" field.</summary>
    public const int PageOffsetFieldNumber = 4;
    private int pageOffset_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int PageOffset {
      get { return pageOffset_; }
      set {
        pageOffset_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetAssetDigestResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetAssetDigestResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!digest_.Equals(other.digest_)) return false;
      if (TimestampMs != other.TimestampMs) return false;
      if (Result != other.Result) return false;
      if (PageOffset != other.PageOffset) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= digest_.GetHashCode();
      if (TimestampMs != 0UL) hash ^= TimestampMs.GetHashCode();
      if (Result != 0) hash ^= Result.GetHashCode();
      if (PageOffset != 0) hash ^= PageOffset.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      digest_.WriteTo(output, _repeated_digest_codec);
      if (TimestampMs != 0UL) {
        output.WriteRawTag(16);
        output.WriteUInt64(TimestampMs);
      }
      if (Result != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) Result);
      }
      if (PageOffset != 0) {
        output.WriteRawTag(32);
        output.WriteInt32(PageOffset);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += digest_.CalculateSize(_repeated_digest_codec);
      if (TimestampMs != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(TimestampMs);
      }
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (PageOffset != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(PageOffset);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetAssetDigestResponse other) {
      if (other == null) {
        return;
      }
      digest_.Add(other.digest_);
      if (other.TimestampMs != 0UL) {
        TimestampMs = other.TimestampMs;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.PageOffset != 0) {
        PageOffset = other.PageOffset;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            digest_.AddEntriesFrom(input, _repeated_digest_codec);
            break;
          }
          case 16: {
            TimestampMs = input.ReadUInt64();
            break;
          }
          case 24: {
            result_ = (global::POGOProtos.Networking.Responses.GetAssetDigestResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 32: {
            PageOffset = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GetAssetDigestResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("PAGE")] Page = 2,
        [pbr::OriginalName("RETRY")] Retry = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
