// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GetGymBadgeDetailsResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/GetGymBadgeDetailsResponse.proto</summary>
  public static partial class GetGymBadgeDetailsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/GetGymBadgeDetailsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GetGymBadgeDetailsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkBQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL0dldEd5bUJhZGdl",
            "RGV0YWlsc1Jlc3BvbnNlLnByb3RvEh9QT0dPUHJvdG9zLk5ldHdvcmtpbmcu",
            "UmVzcG9uc2VzGitQT0dPUHJvdG9zL0RhdGEvQmFkZ2UvQXdhcmRlZEd5bUJh",
            "ZGdlLnByb3RvGiVQT0dPUHJvdG9zL0RhdGEvR3ltL0d5bURlZmVuZGVyLnBy",
            "b3RvIqABChpHZXRHeW1CYWRnZURldGFpbHNSZXNwb25zZRI5CglneW1fYmFk",
            "Z2UYASABKAsyJi5QT0dPUHJvdG9zLkRhdGEuQmFkZ2UuQXdhcmRlZEd5bUJh",
            "ZGdlEjYKDGd5bV9kZWZlbmRlchgCIAEoCzIgLlBPR09Qcm90b3MuRGF0YS5H",
            "eW0uR3ltRGVmZW5kZXISDwoHc3VjY2VzcxgDIAEoCGIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Badge.AwardedGymBadgeReflection.Descriptor, global::POGOProtos.Data.Gym.GymDefenderReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.GetGymBadgeDetailsResponse), global::POGOProtos.Networking.Responses.GetGymBadgeDetailsResponse.Parser, new[]{ "GymBadge", "GymDefender", "Success" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GetGymBadgeDetailsResponse : pb::IMessage<GetGymBadgeDetailsResponse> {
    private static readonly pb::MessageParser<GetGymBadgeDetailsResponse> _parser = new pb::MessageParser<GetGymBadgeDetailsResponse>(() => new GetGymBadgeDetailsResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GetGymBadgeDetailsResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.GetGymBadgeDetailsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetGymBadgeDetailsResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetGymBadgeDetailsResponse(GetGymBadgeDetailsResponse other) : this() {
      GymBadge = other.gymBadge_ != null ? other.GymBadge.Clone() : null;
      GymDefender = other.gymDefender_ != null ? other.GymDefender.Clone() : null;
      success_ = other.success_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GetGymBadgeDetailsResponse Clone() {
      return new GetGymBadgeDetailsResponse(this);
    }

    /// <summary>Field number for the "gym_badge" field.</summary>
    public const int GymBadgeFieldNumber = 1;
    private global::POGOProtos.Data.Badge.AwardedGymBadge gymBadge_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Badge.AwardedGymBadge GymBadge {
      get { return gymBadge_; }
      set {
        gymBadge_ = value;
      }
    }

    /// <summary>Field number for the "gym_defender" field.</summary>
    public const int GymDefenderFieldNumber = 2;
    private global::POGOProtos.Data.Gym.GymDefender gymDefender_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Gym.GymDefender GymDefender {
      get { return gymDefender_; }
      set {
        gymDefender_ = value;
      }
    }

    /// <summary>Field number for the "success" field.</summary>
    public const int SuccessFieldNumber = 3;
    private bool success_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Success {
      get { return success_; }
      set {
        success_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GetGymBadgeDetailsResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GetGymBadgeDetailsResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (!object.Equals(GymBadge, other.GymBadge)) return false;
      if (!object.Equals(GymDefender, other.GymDefender)) return false;
      if (Success != other.Success) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (gymBadge_ != null) hash ^= GymBadge.GetHashCode();
      if (gymDefender_ != null) hash ^= GymDefender.GetHashCode();
      if (Success != false) hash ^= Success.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (gymBadge_ != null) {
        output.WriteRawTag(10);
        output.WriteMessage(GymBadge);
      }
      if (gymDefender_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(GymDefender);
      }
      if (Success != false) {
        output.WriteRawTag(24);
        output.WriteBool(Success);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (gymBadge_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GymBadge);
      }
      if (gymDefender_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GymDefender);
      }
      if (Success != false) {
        size += 1 + 1;
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GetGymBadgeDetailsResponse other) {
      if (other == null) {
        return;
      }
      if (other.gymBadge_ != null) {
        if (gymBadge_ == null) {
          gymBadge_ = new global::POGOProtos.Data.Badge.AwardedGymBadge();
        }
        GymBadge.MergeFrom(other.GymBadge);
      }
      if (other.gymDefender_ != null) {
        if (gymDefender_ == null) {
          gymDefender_ = new global::POGOProtos.Data.Gym.GymDefender();
        }
        GymDefender.MergeFrom(other.GymDefender);
      }
      if (other.Success != false) {
        Success = other.Success;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            if (gymBadge_ == null) {
              gymBadge_ = new global::POGOProtos.Data.Badge.AwardedGymBadge();
            }
            input.ReadMessage(gymBadge_);
            break;
          }
          case 18: {
            if (gymDefender_ == null) {
              gymDefender_ = new global::POGOProtos.Data.Gym.GymDefender();
            }
            input.ReadMessage(gymDefender_);
            break;
          }
          case 24: {
            Success = input.ReadBool();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
