// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/GymBattleAttackResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/GymBattleAttackResponse.proto</summary>
  public static partial class GymBattleAttackResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/GymBattleAttackResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static GymBattleAttackResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj1QT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL0d5bUJhdHRsZUF0",
            "dGFja1Jlc3BvbnNlLnByb3RvEh9QT0dPUHJvdG9zLk5ldHdvcmtpbmcuUmVz",
            "cG9uc2VzGilQT0dPUHJvdG9zL0RhdGEvQmF0dGxlL0JhdHRsZVVwZGF0ZS5w",
            "cm90bxorUE9HT1Byb3Rvcy9EYXRhL0JhZGdlL0F3YXJkZWRHeW1CYWRnZS5w",
            "cm90byLzAgoXR3ltQmF0dGxlQXR0YWNrUmVzcG9uc2USTwoGcmVzdWx0GAEg",
            "ASgOMj8uUE9HT1Byb3Rvcy5OZXR3b3JraW5nLlJlc3BvbnNlcy5HeW1CYXR0",
            "bGVBdHRhY2tSZXNwb25zZS5SZXN1bHQSOwoNYmF0dGxlX3VwZGF0ZRgCIAEo",
            "CzIkLlBPR09Qcm90b3MuRGF0YS5CYXR0bGUuQmF0dGxlVXBkYXRlEjkKCWd5",
            "bV9iYWRnZRgDIAEoCzImLlBPR09Qcm90b3MuRGF0YS5CYWRnZS5Bd2FyZGVk",
            "R3ltQmFkZ2UijgEKBlJlc3VsdBIJCgVVTlNFVBAAEgsKB1NVQ0NFU1MQARIg",
            "ChxFUlJPUl9JTlZBTElEX0FUVEFDS19BQ1RJT05TEAISFgoSRVJST1JfTk9U",
            "X0lOX1JBTkdFEAMSGwoXRVJST1JfV1JPTkdfQkFUVExFX1RZUEUQBBIVChFF",
            "UlJPUl9SQUlEX0FDVElWRRAFYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Battle.BattleUpdateReflection.Descriptor, global::POGOProtos.Data.Badge.AwardedGymBadgeReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.GymBattleAttackResponse), global::POGOProtos.Networking.Responses.GymBattleAttackResponse.Parser, new[]{ "Result", "BattleUpdate", "GymBadge" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.GymBattleAttackResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class GymBattleAttackResponse : pb::IMessage<GymBattleAttackResponse> {
    private static readonly pb::MessageParser<GymBattleAttackResponse> _parser = new pb::MessageParser<GymBattleAttackResponse>(() => new GymBattleAttackResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<GymBattleAttackResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.GymBattleAttackResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GymBattleAttackResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GymBattleAttackResponse(GymBattleAttackResponse other) : this() {
      result_ = other.result_;
      BattleUpdate = other.battleUpdate_ != null ? other.BattleUpdate.Clone() : null;
      GymBadge = other.gymBadge_ != null ? other.GymBadge.Clone() : null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public GymBattleAttackResponse Clone() {
      return new GymBattleAttackResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.GymBattleAttackResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.GymBattleAttackResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "battle_update" field.</summary>
    public const int BattleUpdateFieldNumber = 2;
    private global::POGOProtos.Data.Battle.BattleUpdate battleUpdate_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Battle.BattleUpdate BattleUpdate {
      get { return battleUpdate_; }
      set {
        battleUpdate_ = value;
      }
    }

    /// <summary>Field number for the "gym_badge" field.</summary>
    public const int GymBadgeFieldNumber = 3;
    private global::POGOProtos.Data.Badge.AwardedGymBadge gymBadge_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Badge.AwardedGymBadge GymBadge {
      get { return gymBadge_; }
      set {
        gymBadge_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as GymBattleAttackResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(GymBattleAttackResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(BattleUpdate, other.BattleUpdate)) return false;
      if (!object.Equals(GymBadge, other.GymBadge)) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (battleUpdate_ != null) hash ^= BattleUpdate.GetHashCode();
      if (gymBadge_ != null) hash ^= GymBadge.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (battleUpdate_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(BattleUpdate);
      }
      if (gymBadge_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(GymBadge);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (battleUpdate_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(BattleUpdate);
      }
      if (gymBadge_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(GymBadge);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(GymBattleAttackResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.battleUpdate_ != null) {
        if (battleUpdate_ == null) {
          battleUpdate_ = new global::POGOProtos.Data.Battle.BattleUpdate();
        }
        BattleUpdate.MergeFrom(other.BattleUpdate);
      }
      if (other.gymBadge_ != null) {
        if (gymBadge_ == null) {
          gymBadge_ = new global::POGOProtos.Data.Badge.AwardedGymBadge();
        }
        GymBadge.MergeFrom(other.GymBadge);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.GymBattleAttackResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (battleUpdate_ == null) {
              battleUpdate_ = new global::POGOProtos.Data.Battle.BattleUpdate();
            }
            input.ReadMessage(battleUpdate_);
            break;
          }
          case 26: {
            if (gymBadge_ == null) {
              gymBadge_ = new global::POGOProtos.Data.Badge.AwardedGymBadge();
            }
            input.ReadMessage(gymBadge_);
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the GymBattleAttackResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("ERROR_INVALID_ATTACK_ACTIONS")] ErrorInvalidAttackActions = 2,
        [pbr::OriginalName("ERROR_NOT_IN_RANGE")] ErrorNotInRange = 3,
        [pbr::OriginalName("ERROR_WRONG_BATTLE_TYPE")] ErrorWrongBattleType = 4,
        [pbr::OriginalName("ERROR_RAID_ACTIVE")] ErrorRaidActive = 5,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
