// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/IncenseEncounterResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/IncenseEncounterResponse.proto</summary>
  public static partial class IncenseEncounterResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/IncenseEncounterResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static IncenseEncounterResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cj5QT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL0luY2Vuc2VFbmNv",
            "dW50ZXJSZXNwb25zZS5wcm90bxIfUE9HT1Byb3Rvcy5OZXR3b3JraW5nLlJl",
            "c3BvbnNlcxowUE9HT1Byb3Rvcy9EYXRhL0NhcHR1cmUvQ2FwdHVyZVByb2Jh",
            "YmlsaXR5LnByb3RvGiFQT0dPUHJvdG9zL0RhdGEvUG9rZW1vbkRhdGEucHJv",
            "dG8aJlBPR09Qcm90b3MvSW52ZW50b3J5L0l0ZW0vSXRlbUlkLnByb3RvItAD",
            "ChhJbmNlbnNlRW5jb3VudGVyUmVzcG9uc2USUAoGcmVzdWx0GAEgASgOMkAu",
            "UE9HT1Byb3Rvcy5OZXR3b3JraW5nLlJlc3BvbnNlcy5JbmNlbnNlRW5jb3Vu",
            "dGVyUmVzcG9uc2UuUmVzdWx0EjIKDHBva2Vtb25fZGF0YRgCIAEoCzIcLlBP",
            "R09Qcm90b3MuRGF0YS5Qb2tlbW9uRGF0YRJIChNjYXB0dXJlX3Byb2JhYmls",
            "aXR5GAMgASgLMisuUE9HT1Byb3Rvcy5EYXRhLkNhcHR1cmUuQ2FwdHVyZVBy",
            "b2JhYmlsaXR5EjYKC2FjdGl2ZV9pdGVtGAQgASgOMiEuUE9HT1Byb3Rvcy5J",
            "bnZlbnRvcnkuSXRlbS5JdGVtSWQSIgoaYXJwbHVzX2F0dGVtcHRzX3VudGls",
            "X2ZsZWUYBSABKAUihwEKBlJlc3VsdBIdChlJTkNFTlNFX0VOQ09VTlRFUl9V",
            "TktOT1dOEAASHQoZSU5DRU5TRV9FTkNPVU5URVJfU1VDQ0VTUxABEiMKH0lO",
            "Q0VOU0VfRU5DT1VOVEVSX05PVF9BVkFJTEFCTEUQAhIaChZQT0tFTU9OX0lO",
            "VkVOVE9SWV9GVUxMEANiBnByb3RvMw=="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { global::POGOProtos.Data.Capture.CaptureProbabilityReflection.Descriptor, global::POGOProtos.Data.PokemonDataReflection.Descriptor, global::POGOProtos.Inventory.Item.ItemIdReflection.Descriptor, },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.IncenseEncounterResponse), global::POGOProtos.Networking.Responses.IncenseEncounterResponse.Parser, new[]{ "Result", "PokemonData", "CaptureProbability", "ActiveItem", "ArplusAttemptsUntilFlee" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.IncenseEncounterResponse.Types.Result) }, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class IncenseEncounterResponse : pb::IMessage<IncenseEncounterResponse> {
    private static readonly pb::MessageParser<IncenseEncounterResponse> _parser = new pb::MessageParser<IncenseEncounterResponse>(() => new IncenseEncounterResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<IncenseEncounterResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.IncenseEncounterResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IncenseEncounterResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IncenseEncounterResponse(IncenseEncounterResponse other) : this() {
      result_ = other.result_;
      PokemonData = other.pokemonData_ != null ? other.PokemonData.Clone() : null;
      CaptureProbability = other.captureProbability_ != null ? other.CaptureProbability.Clone() : null;
      activeItem_ = other.activeItem_;
      arplusAttemptsUntilFlee_ = other.arplusAttemptsUntilFlee_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public IncenseEncounterResponse Clone() {
      return new IncenseEncounterResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.IncenseEncounterResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.IncenseEncounterResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    /// <summary>Field number for the "pokemon_data" field.</summary>
    public const int PokemonDataFieldNumber = 2;
    private global::POGOProtos.Data.PokemonData pokemonData_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.PokemonData PokemonData {
      get { return pokemonData_; }
      set {
        pokemonData_ = value;
      }
    }

    /// <summary>Field number for the "capture_probability" field.</summary>
    public const int CaptureProbabilityFieldNumber = 3;
    private global::POGOProtos.Data.Capture.CaptureProbability captureProbability_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Data.Capture.CaptureProbability CaptureProbability {
      get { return captureProbability_; }
      set {
        captureProbability_ = value;
      }
    }

    /// <summary>Field number for the "active_item" field.</summary>
    public const int ActiveItemFieldNumber = 4;
    private global::POGOProtos.Inventory.Item.ItemId activeItem_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Inventory.Item.ItemId ActiveItem {
      get { return activeItem_; }
      set {
        activeItem_ = value;
      }
    }

    /// <summary>Field number for the "arplus_attempts_until_flee" field.</summary>
    public const int ArplusAttemptsUntilFleeFieldNumber = 5;
    private int arplusAttemptsUntilFlee_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int ArplusAttemptsUntilFlee {
      get { return arplusAttemptsUntilFlee_; }
      set {
        arplusAttemptsUntilFlee_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as IncenseEncounterResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(IncenseEncounterResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      if (!object.Equals(PokemonData, other.PokemonData)) return false;
      if (!object.Equals(CaptureProbability, other.CaptureProbability)) return false;
      if (ActiveItem != other.ActiveItem) return false;
      if (ArplusAttemptsUntilFlee != other.ArplusAttemptsUntilFlee) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      if (pokemonData_ != null) hash ^= PokemonData.GetHashCode();
      if (captureProbability_ != null) hash ^= CaptureProbability.GetHashCode();
      if (ActiveItem != 0) hash ^= ActiveItem.GetHashCode();
      if (ArplusAttemptsUntilFlee != 0) hash ^= ArplusAttemptsUntilFlee.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
      if (pokemonData_ != null) {
        output.WriteRawTag(18);
        output.WriteMessage(PokemonData);
      }
      if (captureProbability_ != null) {
        output.WriteRawTag(26);
        output.WriteMessage(CaptureProbability);
      }
      if (ActiveItem != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) ActiveItem);
      }
      if (ArplusAttemptsUntilFlee != 0) {
        output.WriteRawTag(40);
        output.WriteInt32(ArplusAttemptsUntilFlee);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      if (pokemonData_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(PokemonData);
      }
      if (captureProbability_ != null) {
        size += 1 + pb::CodedOutputStream.ComputeMessageSize(CaptureProbability);
      }
      if (ActiveItem != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) ActiveItem);
      }
      if (ArplusAttemptsUntilFlee != 0) {
        size += 1 + pb::CodedOutputStream.ComputeInt32Size(ArplusAttemptsUntilFlee);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(IncenseEncounterResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
      if (other.pokemonData_ != null) {
        if (pokemonData_ == null) {
          pokemonData_ = new global::POGOProtos.Data.PokemonData();
        }
        PokemonData.MergeFrom(other.PokemonData);
      }
      if (other.captureProbability_ != null) {
        if (captureProbability_ == null) {
          captureProbability_ = new global::POGOProtos.Data.Capture.CaptureProbability();
        }
        CaptureProbability.MergeFrom(other.CaptureProbability);
      }
      if (other.ActiveItem != 0) {
        ActiveItem = other.ActiveItem;
      }
      if (other.ArplusAttemptsUntilFlee != 0) {
        ArplusAttemptsUntilFlee = other.ArplusAttemptsUntilFlee;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.IncenseEncounterResponse.Types.Result) input.ReadEnum();
            break;
          }
          case 18: {
            if (pokemonData_ == null) {
              pokemonData_ = new global::POGOProtos.Data.PokemonData();
            }
            input.ReadMessage(pokemonData_);
            break;
          }
          case 26: {
            if (captureProbability_ == null) {
              captureProbability_ = new global::POGOProtos.Data.Capture.CaptureProbability();
            }
            input.ReadMessage(captureProbability_);
            break;
          }
          case 32: {
            activeItem_ = (global::POGOProtos.Inventory.Item.ItemId) input.ReadEnum();
            break;
          }
          case 40: {
            ArplusAttemptsUntilFlee = input.ReadInt32();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the IncenseEncounterResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("INCENSE_ENCOUNTER_UNKNOWN")] IncenseEncounterUnknown = 0,
        [pbr::OriginalName("INCENSE_ENCOUNTER_SUCCESS")] IncenseEncounterSuccess = 1,
        [pbr::OriginalName("INCENSE_ENCOUNTER_NOT_AVAILABLE")] IncenseEncounterNotAvailable = 2,
        [pbr::OriginalName("POKEMON_INVENTORY_FULL")] PokemonInventoryFull = 3,
      }

    }
    #endregion

  }

  #endregion

}

#endregion Designer generated code
