// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: POGOProtos/Networking/Responses/PlatformClientActionsResponse.proto
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace POGOProtos.Networking.Responses {

  /// <summary>Holder for reflection information generated from POGOProtos/Networking/Responses/PlatformClientActionsResponse.proto</summary>
  public static partial class PlatformClientActionsResponseReflection {

    #region Descriptor
    /// <summary>File descriptor for POGOProtos/Networking/Responses/PlatformClientActionsResponse.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static PlatformClientActionsResponseReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "CkNQT0dPUHJvdG9zL05ldHdvcmtpbmcvUmVzcG9uc2VzL1BsYXRmb3JtQ2xp",
            "ZW50QWN0aW9uc1Jlc3BvbnNlLnByb3RvEh9QT0dPUHJvdG9zLk5ldHdvcmtp",
            "bmcuUmVzcG9uc2VzIq0BCiBSZWdpc3RlclB1c2hOb3RpZmljYXRpb25SZXNw",
            "b25zZRJYCgZyZXN1bHQYASABKA4ySC5QT0dPUHJvdG9zLk5ldHdvcmtpbmcu",
            "UmVzcG9uc2VzLlJlZ2lzdGVyUHVzaE5vdGlmaWNhdGlvblJlc3BvbnNlLlJl",
            "c3VsdCIvCgZSZXN1bHQSCQoFVU5TRVQQABILCgdTVUNDRVNTEAESDQoJTk9f",
            "Q0hBTkdFEAIi7wEKIFVwZGF0ZU5vdGlmaWNhdGlvblN0YXR1c1Jlc3BvbnNl",
            "EhgKEG5vdGlmaWNhdGlvbl9pZHMYASADKAkSGwoTY3JlYXRlX3RpbWVzdGFt",
            "cF9tcxgCIAMoAxJiCgVzdGF0ZRgDIAEoDjJTLlBPR09Qcm90b3MuTmV0d29y",
            "a2luZy5SZXNwb25zZXMuVXBkYXRlTm90aWZpY2F0aW9uU3RhdHVzUmVzcG9u",
            "c2UuTm90aWZpY2F0aW9uU3RhdGUiMAoRTm90aWZpY2F0aW9uU3RhdGUSDwoL",
            "VU5TRVRfU1RBVEUQABIKCgZWSUVXRUQQASIoCiZPcHRPdXRQdXNoTm90aWZp",
            "Y2F0aW9uQ2F0ZWdvcnlSZXNwb25zZWIGcHJvdG8z"));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(null, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.RegisterPushNotificationResponse), global::POGOProtos.Networking.Responses.RegisterPushNotificationResponse.Parser, new[]{ "Result" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.RegisterPushNotificationResponse.Types.Result) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.UpdateNotificationStatusResponse), global::POGOProtos.Networking.Responses.UpdateNotificationStatusResponse.Parser, new[]{ "NotificationIds", "CreateTimestampMs", "State" }, null, new[]{ typeof(global::POGOProtos.Networking.Responses.UpdateNotificationStatusResponse.Types.NotificationState) }, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::POGOProtos.Networking.Responses.OptOutPushNotificationCategoryResponse), global::POGOProtos.Networking.Responses.OptOutPushNotificationCategoryResponse.Parser, null, null, null, null)
          }));
    }
    #endregion

  }
  #region Messages
  public sealed partial class RegisterPushNotificationResponse : pb::IMessage<RegisterPushNotificationResponse> {
    private static readonly pb::MessageParser<RegisterPushNotificationResponse> _parser = new pb::MessageParser<RegisterPushNotificationResponse>(() => new RegisterPushNotificationResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<RegisterPushNotificationResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.PlatformClientActionsResponseReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterPushNotificationResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterPushNotificationResponse(RegisterPushNotificationResponse other) : this() {
      result_ = other.result_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public RegisterPushNotificationResponse Clone() {
      return new RegisterPushNotificationResponse(this);
    }

    /// <summary>Field number for the "result" field.</summary>
    public const int ResultFieldNumber = 1;
    private global::POGOProtos.Networking.Responses.RegisterPushNotificationResponse.Types.Result result_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.RegisterPushNotificationResponse.Types.Result Result {
      get { return result_; }
      set {
        result_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as RegisterPushNotificationResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(RegisterPushNotificationResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Result != other.Result) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Result != 0) hash ^= Result.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Result != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Result);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Result != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Result);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(RegisterPushNotificationResponse other) {
      if (other == null) {
        return;
      }
      if (other.Result != 0) {
        Result = other.Result;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 8: {
            result_ = (global::POGOProtos.Networking.Responses.RegisterPushNotificationResponse.Types.Result) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the RegisterPushNotificationResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum Result {
        [pbr::OriginalName("UNSET")] Unset = 0,
        [pbr::OriginalName("SUCCESS")] Success = 1,
        [pbr::OriginalName("NO_CHANGE")] NoChange = 2,
      }

    }
    #endregion

  }

  public sealed partial class UpdateNotificationStatusResponse : pb::IMessage<UpdateNotificationStatusResponse> {
    private static readonly pb::MessageParser<UpdateNotificationStatusResponse> _parser = new pb::MessageParser<UpdateNotificationStatusResponse>(() => new UpdateNotificationStatusResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<UpdateNotificationStatusResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.PlatformClientActionsResponseReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateNotificationStatusResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateNotificationStatusResponse(UpdateNotificationStatusResponse other) : this() {
      notificationIds_ = other.notificationIds_.Clone();
      createTimestampMs_ = other.createTimestampMs_.Clone();
      state_ = other.state_;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public UpdateNotificationStatusResponse Clone() {
      return new UpdateNotificationStatusResponse(this);
    }

    /// <summary>Field number for the "notification_ids" field.</summary>
    public const int NotificationIdsFieldNumber = 1;
    private static readonly pb::FieldCodec<string> _repeated_notificationIds_codec
        = pb::FieldCodec.ForString(10);
    private readonly pbc::RepeatedField<string> notificationIds_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> NotificationIds {
      get { return notificationIds_; }
    }

    /// <summary>Field number for the "create_timestamp_ms" field.</summary>
    public const int CreateTimestampMsFieldNumber = 2;
    private static readonly pb::FieldCodec<long> _repeated_createTimestampMs_codec
        = pb::FieldCodec.ForInt64(18);
    private readonly pbc::RepeatedField<long> createTimestampMs_ = new pbc::RepeatedField<long>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<long> CreateTimestampMs {
      get { return createTimestampMs_; }
    }

    /// <summary>Field number for the "state" field.</summary>
    public const int StateFieldNumber = 3;
    private global::POGOProtos.Networking.Responses.UpdateNotificationStatusResponse.Types.NotificationState state_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::POGOProtos.Networking.Responses.UpdateNotificationStatusResponse.Types.NotificationState State {
      get { return state_; }
      set {
        state_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as UpdateNotificationStatusResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(UpdateNotificationStatusResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if(!notificationIds_.Equals(other.notificationIds_)) return false;
      if(!createTimestampMs_.Equals(other.createTimestampMs_)) return false;
      if (State != other.State) return false;
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      hash ^= notificationIds_.GetHashCode();
      hash ^= createTimestampMs_.GetHashCode();
      if (State != 0) hash ^= State.GetHashCode();
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      notificationIds_.WriteTo(output, _repeated_notificationIds_codec);
      createTimestampMs_.WriteTo(output, _repeated_createTimestampMs_codec);
      if (State != 0) {
        output.WriteRawTag(24);
        output.WriteEnum((int) State);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      size += notificationIds_.CalculateSize(_repeated_notificationIds_codec);
      size += createTimestampMs_.CalculateSize(_repeated_createTimestampMs_codec);
      if (State != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) State);
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(UpdateNotificationStatusResponse other) {
      if (other == null) {
        return;
      }
      notificationIds_.Add(other.notificationIds_);
      createTimestampMs_.Add(other.createTimestampMs_);
      if (other.State != 0) {
        State = other.State;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
          case 10: {
            notificationIds_.AddEntriesFrom(input, _repeated_notificationIds_codec);
            break;
          }
          case 18:
          case 16: {
            createTimestampMs_.AddEntriesFrom(input, _repeated_createTimestampMs_codec);
            break;
          }
          case 24: {
            state_ = (global::POGOProtos.Networking.Responses.UpdateNotificationStatusResponse.Types.NotificationState) input.ReadEnum();
            break;
          }
        }
      }
    }

    #region Nested types
    /// <summary>Container for nested types declared in the UpdateNotificationStatusResponse message type.</summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static partial class Types {
      public enum NotificationState {
        [pbr::OriginalName("UNSET_STATE")] UnsetState = 0,
        [pbr::OriginalName("VIEWED")] Viewed = 1,
      }

    }
    #endregion

  }

  public sealed partial class OptOutPushNotificationCategoryResponse : pb::IMessage<OptOutPushNotificationCategoryResponse> {
    private static readonly pb::MessageParser<OptOutPushNotificationCategoryResponse> _parser = new pb::MessageParser<OptOutPushNotificationCategoryResponse>(() => new OptOutPushNotificationCategoryResponse());
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<OptOutPushNotificationCategoryResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::POGOProtos.Networking.Responses.PlatformClientActionsResponseReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OptOutPushNotificationCategoryResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OptOutPushNotificationCategoryResponse(OptOutPushNotificationCategoryResponse other) : this() {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public OptOutPushNotificationCategoryResponse Clone() {
      return new OptOutPushNotificationCategoryResponse(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as OptOutPushNotificationCategoryResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(OptOutPushNotificationCategoryResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      return true;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(OptOutPushNotificationCategoryResponse other) {
      if (other == null) {
        return;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            input.SkipLastField();
            break;
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
